service:
  name: fusion-lambdas
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:InvokeFunction"
        - "lambda:InvokeAsync"
      Resource: "*"
    - Effect: Allow
      Action:
        - "s3:PutObject"
      Resource: "*"
    - Effect: Allow
      Action:
        - "logs:*"
      Resource: "*"
package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - node_modules/aws-sdk/**
functions:
  handler0:
    handler: src/fusionHandler.handler
    name: handler0
    timeout: 60
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            target: screenshot
  handler1:
    handler: src/fusionHandler.handler
    name: handler1
    timeout: 60
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            target: screenshot
  handler2:
    handler: src/fusionHandler.handler
    name: handler2
    timeout: 60
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: true
          input:
            target: screenshot
